class_name Enums
extends Reference

enum Actor { ENVIRONMENT, PLAYER, ENEMY }

enum CardSuperType { OFFICER, CREW, EVENT }

enum CardSubType { CAPTAIN, COMMANDER, SHIP, INSTANT, ONGOING }

enum ShipSuperType { SCOUT, CRUISER, CAPITAL_SHIP }

enum ShipSubType {
	CORVETTE,
	FRIGATE,
	DESTROYER,
	LIGHT_CRUISER,
	HEAVY_CRUISER,
	BATTLE_CRUISER,
	BATTLESHIP,
	DREADNOUGHT,
	CARRIER
}
