class_name Enums
extends Reference

enum Actor { ENVIRONMENT, PLAYER, ENEMY }

enum ActionType { ATTACK, MOVE, SCOUT, CONTROL }

enum CardSuperType { OFFICER, CREW, EVENT, VOID }

enum CardSubType { CAPTAIN, COMMANDER, SHIP, INSTANT, ONGOING, VOID }

enum ShipSuperType { SCOUT, CRUISER, CAPITAL_SHIP }

enum ShipSubType {
	CORVETTE,
	FRIGATE,
	DESTROYER,
	LIGHT_CRUISER,
	HEAVY_CRUISER,
	BATTLE_CRUISER,
	BATTLESHIP,
	DREADNOUGHT,
	CARRIER
}

enum ShipActionType { NONE, ATTACK, MOVE, SCAN, SCOUT }

enum CombatState {
	PAUSED,
	PLAYER_TURN_UNFOCUSED,
	PLAYER_TURN_CARD_SELECTED,
	PLAYER_TURN_ACTION_SELECTED,
	PLAYER_TURN_ACTION_RESOLVING,
	ANY
}
